# Use an official node runtime as a parent image
FROM node:18.16-alpine3.18

ENV DOCKER=true

# Install git
RUN apk --no-cache add git

# Install Python
RUN apk add g++ make py3-pip

# Set the working directory to /app
WORKDIR /app

RUN npm install solc@0.8.7
RUN npm install solc@0.5.15

# Install any needed packages specified in package.json
COPY ./package.json ./
RUN yarn

# Copy the current directory contents into the container at /app
COPY . /app

CMD ["hardhat", "run", "scripts/local-setup.ts", "--network", "docker"]

# Use the script as the entrypoint
ENTRYPOINT ["npx"]
